apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-project
  namespace: flux-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-project
  template:
    metadata:
      labels:
        app: nginx-project
    spec:
      containers:
        - name: nginx
          image: khushiporwal/sample-app:18
          ports:
            - containerPort: 80
----
apiVersion: v1
kind: Service
metadata:
  name: nginx-project
  namespace: flux-system
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: nginx-project
