apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  namespace: flux-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-project
  template:
    metadata:
      labels:
        app: nginx-project
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-project
  namespace: flux-system
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: nginx-project






