---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: test-deployment
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: main
  url: https://github.com/gem-khushiporwal/test_deployment.git
